services:
  fsharp-starter-api:
    image: ${FSHARP_STARTER_IMAGE}
    container_name: fsharp-starter-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Data Source=/app/data/fsharp-starter.db
    volumes:
      - ${FSHARP_STARTER_DATA_ROOT:-/mnt/fsharp-starter-data}/fsharp-starter-db:/app/data
    restart: unless-stopped
